### ISSUE TITLE
Backwards evilness logic

### ISSUE THREAD

**Issue by BenoitKnecht** [mathiasbynens/evil.sh#66]
Looking at the way `EVIL_BEHAVIOUR` is processed, it seems that the evil level is backwards. For instance, if `EVIL_BEHAVIOUR=annoying`, then `annoying()`, `destructive()`, `devasting()` and `unusable()` all return `true`, whereas I would expect only `insane()` and `annoying()` to be `true` in that case.

So if someone only intended to play a small prank on someone by keeping the default `EVIL_BEHAVIOUR=annoying`, they would actually be running everything up to the `unusable` level, and probably destroy that person's system.

**Comment by benaryorg** [comment]
Would you be so kind as to review the PR I've sent in.
When I introduced the change apparently noone reviewed it.
